set -g default-terminal "tmux-256color"
set -g focus-events on
set -sg escape-time 10
set -g mouse on

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g pane-border-style "fg=#1a1a1a"
set -g pane-active-border-style "fg=#c4c4c4"
set -g window-style "bg=default"
set -g window-active-style "bg=default"

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=#a6a6a6,fg=#080808"
set -g status-left-length 80
set -g status-right-length 20
set -g status-left "#[bg=#a6a6a6,fg=#080808][#S] [#W]"
set -g status-right "#[bg=#a6a6a6,fg=#080808]%H:%M"
set -g window-status-format ""
set -g window-status-current-format ""
set -g message-style "bg=#1a1a1a,fg=#c4c4c4"
set -g mode-style "bg=#c4c4c4,fg=#080808"
